name: Bellezza Botanicals
favicon: null
layout_spectrum: 0.28473203675821424
typography_spectrum: 0.8663181958254427
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7873477812390774
  lightness: 0.9471091323066503
  saturation: 0.38955374993383884
  rhythmicContrast: 0.696080750785768
purpose: []
